"""empty message

Revision ID: cf16a175ad7a
Revises: 5e7611f81036
Create Date: 2017-09-09 13:38:12.600253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf16a175ad7a'
down_revision = '5e7611f81036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.drop_column('question', 'creare_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('creare_time', mysql.DATETIME(), nullable=True))
    op.drop_column('question', 'create_time')
    # ### end Alembic commands ###
